"""
extraction_service.py
---------------------
Single responsibility: take PII-redacted text and return structured metadata
via a single GPT-4o call.

Public surface
--------------
    extract(clean_text, current_date, timezone) -> ExtractionResult

Dataclass
---------
    ExtractionResult — type, entry_date, extracted_fields (dict), tags.

Exceptions
----------
    ExtractionError — any OpenAI / parsing failure during extraction.

Design notes
~~~~~~~~~~~~
* Uses the architecture-spec prompt (Section 8 of heypoco_architecture.md).
* The prompt asks GPT-4o to resolve relative dates ("yesterday", "last week")
  against the supplied *current_date* + *timezone*.
* extracted_fields is returned as a plain ``dict`` (JSONB-ready) — not a
  Pydantic model — because the keys differ per entry type and we don't want
  to force-fit every domain into one class.
* If GPT-4o returns garbage or the call fails, the function raises
  ``ExtractionError`` so the caller can fall back to ``type = "general"``.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional

from openai import AsyncOpenAI, APIError, AuthenticationError

from app.config import get_settings

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Custom exception
# ---------------------------------------------------------------------------


class ExtractionError(Exception):
    """
    Raised when the GPT-4o extraction call fails or the response cannot
    be parsed into the expected JSON shape.

    The original exception (if any) is attached via ``__cause__``.
    """


# ---------------------------------------------------------------------------
# Output dataclass
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ExtractionResult:
    """
    Structured output from a single GPT-4o extraction call.

    Attributes:
        type:             One of finance | journal | task | event |
                          note | health | general.
        entry_date:       ISO-8601 datetime string inferred from the text
                          (e.g. "2026-02-28T00:00:00").  Falls back to
                          *current_date* when GPT-4o cannot determine one.
        extracted_fields: Domain-specific key-value pairs (see architecture
                          doc §4 for the JSONB contract per type).
        tags:             2-4 short lowercase tags generated by GPT-4o.
    """

    type: str
    entry_date: str
    extracted_fields: Dict[str, Any]
    tags: List[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Valid entry types — used for output validation
# ---------------------------------------------------------------------------

_VALID_TYPES = frozenset({
    "finance", "journal", "task", "event", "note", "health", "general",
})

# ---------------------------------------------------------------------------
# GPT-4o model name
# ---------------------------------------------------------------------------

_EXTRACTION_MODEL = "gpt-4o"


# ---------------------------------------------------------------------------
# Extraction prompt (from heypoco_architecture.md §8)
# ---------------------------------------------------------------------------
# Double-braces {{ }} are literal braces in .format() templates.
# The three placeholders are filled at call time.

_EXTRACTION_PROMPT = """\
You are processing a personal voice log entry for a brain dump app.
Today's date: {current_date}
User timezone: {timezone}

Analyze this entry and return JSON only. No explanation. No markdown.

Input: "{clean_text}"

Return exactly this structure:
{{
  "type": "finance | journal | task | event | note | health | general",
  "entry_date": "ISO 8601 datetime — infer from today/yesterday/tomorrow/last week",
  "extracted_fields": {{
    "amount":       number or null,
    "currency":     "USD | INR | EUR | GBP | AED" or null,
    "merchant":     string or null,
    "category":     "food & drink | shopping | transport | health | entertainment | utilities | other" or null,
    "breakdown":    [] or null,
    "mood":         "positive | negative | neutral" or null,
    "energy":       "high | low | medium" or null,
    "highlights":   [] or null,
    "action":       string or null,
    "deadline":     "ISO date" or null,
    "status":       "open" or null,
    "title":        string or null,
    "scheduled_at": "ISO datetime" or null,
    "person":       string or null,
    "people":       [] or null,
    "symptom":      string or null,
    "medication":   string or null,
    "topic":        string or null
  }},
  "tags": ["2-4 short lowercase tags"]
}}

Rules:
- Return only fields relevant to the type. Omit irrelevant fields entirely.
- Never fabricate data not present in the input.
- If type is unclear, use general.
- For amounts: extract all numbers that represent money.
- For dates: resolve relative terms using today's date provided above.
"""


# ---------------------------------------------------------------------------
# Internal: lazy OpenAI client (same pattern as other services)
# ---------------------------------------------------------------------------

_client: Optional[AsyncOpenAI] = None


def _get_client() -> AsyncOpenAI:
    """
    Return a lazily-initialised AsyncOpenAI client.

    Reads OPENAI_API_KEY from the environment on first call.
    Raises ExtractionError if the key is missing.
    """
    global _client
    if _client is None:
        api_key = get_settings().openai_api_key
        if not api_key:
            raise ExtractionError(
                "OPENAI_API_KEY environment variable is not set. "
                "Add it to your .env file or shell environment."
            )
        _client = AsyncOpenAI(api_key=api_key)
    return _client


# ---------------------------------------------------------------------------
# Internal: response validation helpers
# ---------------------------------------------------------------------------


def _validate_type(raw_type: Any) -> str:
    """Normalise and validate the ``type`` field from GPT-4o output."""
    if not isinstance(raw_type, str):
        return "general"
    normalised = raw_type.strip().lower()
    return normalised if normalised in _VALID_TYPES else "general"


def _validate_entry_date(raw_date: Any, fallback: str, timezone_str: str = "UTC") -> str:
    """
    Return a valid ISO-8601 datetime string normalised to **UTC**.

    GPT-4o typically returns a bare datetime like ``"2026-03-02T00:00:00"``
    without timezone info.  We treat it as local time in *timezone_str*
    (the user's timezone), convert to UTC, and return an explicit UTC
    ISO string.  This ensures ``entry_date`` is always stored as UTC in
    the TIMESTAMPTZ column, making date-range queries straightforward.

    If GPT-4o returned something unparseable, fall back to *fallback*
    (which is the current_date the caller provided) at midnight UTC.
    """
    from zoneinfo import ZoneInfo

    user_tz = ZoneInfo(timezone_str) if timezone_str else ZoneInfo("UTC")
    utc_tz = ZoneInfo("UTC")

    def _to_utc(dt_str: str) -> str:
        """Parse a datetime string, localise to user TZ if naive, convert to UTC."""
        dt = datetime.fromisoformat(dt_str.strip())
        if dt.tzinfo is None:
            # Bare datetime → treat as user's local time
            dt = dt.replace(tzinfo=user_tz)
        return dt.astimezone(utc_tz).isoformat()

    if not isinstance(raw_date, str) or not raw_date.strip():
        # Fallback — current_date is typically "2026-03-02" (date only)
        try:
            return _to_utc(fallback)
        except (ValueError, TypeError):
            return datetime.now(utc_tz).isoformat()

    try:
        return _to_utc(raw_date)
    except (ValueError, TypeError):
        try:
            return _to_utc(fallback)
        except (ValueError, TypeError):
            return datetime.now(utc_tz).isoformat()


def _validate_tags(raw_tags: Any) -> List[str]:
    """Ensure tags is a list of short lowercase strings."""
    if not isinstance(raw_tags, list):
        return []
    # Keep only strings, lowercase, strip whitespace, cap at 6 tags.
    return [str(t).lower().strip() for t in raw_tags if isinstance(t, str)][:6]


def _clean_extracted_fields(raw_fields: Any) -> Dict[str, Any]:
    """
    Strip null-valued and irrelevant keys from extracted_fields so only
    meaningful data is persisted in the JSONB column.
    """
    if not isinstance(raw_fields, dict):
        return {}
    # Remove keys whose value is None, empty string, or empty list.
    return {
        k: v
        for k, v in raw_fields.items()
        if v is not None and v != "" and v != []
    }


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


async def extract(
    clean_text: str,
    current_date: str,
    timezone: str = "UTC",
) -> ExtractionResult:
    """
    Send *clean_text* (PII-redacted) to GPT-4o and return structured
    extraction results.

    Args:
        clean_text:   The user's text **after** PII redaction.
        current_date: ISO-8601 date string for "today" in the user's
                      timezone (e.g. ``"2026-02-28"``).
        timezone:     IANA timezone string (e.g. ``"Asia/Kolkata"``).
                      Used by GPT-4o to resolve relative dates.

    Returns:
        An ``ExtractionResult`` with type, entry_date, extracted_fields,
        and tags.

    Raises:
        ExtractionError: If the OpenAI call fails or the response is
            unparseable.  The caller should fall back to
            ``type = "general"`` in this case.

    Example:
        >>> result = await extract(
        ...     "Spent $60 at Starbucks",
        ...     current_date="2026-02-28",
        ...     timezone="America/New_York",
        ... )
        >>> result.type
        'finance'
        >>> result.extracted_fields["amount"]
        60
    """
    client = _get_client()

    # Build the prompt with the caller's context injected.
    prompt = _EXTRACTION_PROMPT.format(
        current_date=current_date,
        timezone=timezone,
        clean_text=clean_text,
    )

    try:
        response = await client.chat.completions.create(
            model=_EXTRACTION_MODEL,
            messages=[
                {"role": "system", "content": "You are a structured data extraction engine. Return only valid JSON."},
                {"role": "user", "content": prompt},
            ],
            temperature=0.1,                           # deterministic
            response_format={"type": "json_object"},   # force JSON mode
        )
    except AuthenticationError as exc:
        raise ExtractionError(
            f"OpenAI authentication failed — check OPENAI_API_KEY. Detail: {exc}"
        ) from exc
    except APIError as exc:
        raise ExtractionError(
            f"GPT-4o API error during extraction: {exc}"
        ) from exc

    # ------------------------------------------------------------------
    # Parse the JSON response
    # ------------------------------------------------------------------
    raw_content = response.choices[0].message.content
    if not raw_content:
        raise ExtractionError("GPT-4o returned an empty response.")

    try:
        parsed: Dict[str, Any] = json.loads(raw_content)
    except json.JSONDecodeError as exc:
        raise ExtractionError(
            f"GPT-4o response was not valid JSON: {raw_content[:200]}"
        ) from exc

    # ------------------------------------------------------------------
    # Validate & normalise each field
    # ------------------------------------------------------------------
    entry_type = _validate_type(parsed.get("type"))
    entry_date = _validate_entry_date(
        parsed.get("entry_date"), fallback=current_date, timezone_str=timezone,
    )
    extracted_fields = _clean_extracted_fields(parsed.get("extracted_fields"))
    tags = _validate_tags(parsed.get("tags"))

    logger.info(
        "Extraction complete — type=%s, tags=%s, fields_count=%d",
        entry_type,
        tags,
        len(extracted_fields),
    )

    return ExtractionResult(
        type=entry_type,
        entry_date=entry_date,
        extracted_fields=extracted_fields,
        tags=tags,
    )
